# Generated by Django 4.1.2 on 2024-10-20 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='id_categoria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id_email', models.AutoField(db_column='id_email', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=300)),
                ('mensaje', models.CharField(max_length=5000)),
                ('comentario', models.CharField(max_length=500)),
                ('tipo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Ticket',
            fields=[
                ('id_estado', models.AutoField(db_column='id_estado', primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id_prioridad', models.AutoField(db_column='id_prioridad', primary_key=True, serialize=False)),
                ('nombre_SLA', models.CharField(max_length=50)),
                ('respuesta_minutos', models.IntegerField()),
                ('solucion_minutos_min', models.IntegerField()),
                ('solucion_minutos_max', models.IntegerField()),
                ('nivel_prioridad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Sancion',
            fields=[
                ('id_tipo_sancion', models.AutoField(db_column='id_tipo_sancion', primary_key=True, serialize=False)),
                ('ban', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_techsupp', models.BooleanField(default=False)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='pfp/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.AutoField(db_column='id_ticket', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='SAS_tickets.categoria')),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.CASCADE, to='SAS_tickets.estado_ticket')),
                ('id_prioridad', models.ForeignKey(db_column='id_prioridad', on_delete=django.db.models.deletion.CASCADE, to='SAS_tickets.sla')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_as_technician', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_as_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id_sancion', models.AutoField(db_column='id_sancion', primary_key=True, serialize=False)),
                ('duracion_horas', models.IntegerField()),
                ('motivo', models.CharField(max_length=100)),
                ('id_tipo_sancion', models.ForeignKey(db_column='id_tipo_sancion', on_delete=django.db.models.deletion.CASCADE, to='SAS_tickets.tipo_sancion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(db_column='id_reporte', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.FileField(upload_to='reportes/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.AutoField(db_column='id_mensaje', primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=1000)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_ticket', models.ForeignKey(db_column='id_ticket', on_delete=django.db.models.deletion.CASCADE, to='SAS_tickets.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='SAS_tickets.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Log_Email',
            fields=[
                ('id_log_email', models.AutoField(db_column='id_log_email', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_email', models.ForeignKey(db_column='id_email', on_delete=django.db.models.deletion.CASCADE, to='SAS_tickets.email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Foto_Ticket',
            fields=[
                ('id_foto', models.AutoField(db_column='id_foto', primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='ticket_pic/')),
                ('id_mensaje', models.ForeignKey(db_column='id_mensaje', on_delete=django.db.models.deletion.CASCADE, to='SAS_tickets.mensaje')),
                ('id_ticket', models.ForeignKey(db_column='id_ticket', on_delete=django.db.models.deletion.CASCADE, to='SAS_tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Derivacion',
            fields=[
                ('id_derivacion', models.AutoField(db_column='id_derivacion', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('id_ticket', models.ForeignKey(db_column='id_ticket', on_delete=django.db.models.deletion.CASCADE, to='SAS_tickets.ticket')),
                ('tecnico_envia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivaciones_envia', to=settings.AUTH_USER_MODEL)),
                ('tecnico_recibe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivaciones_recibe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_tecnico',
            fields=[
                ('id_asignacion', models.AutoField(db_column='id_asignacion', primary_key=True, serialize=False)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='SAS_tickets.categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_categoria', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_categoria', to='SAS_tickets.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id_accion', models.AutoField(db_column='id_reporte', primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
